# application-localstack.yml
app:
  storage:
    type: s3
    s3:
      bucket: product-images
      region: us-east-1
      endpoint: http://localhost:4566

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB